#!/usr/bin/env bun
/**
 * Generates an expanded STATIC_TOKEN_DECIMALS map for Polygon.
 *
 * Pulls from several free, public token lists (no API keys required).
 * Run with: bun run scripts/generate-polygon-tokens.ts > src/effects/token_registry.ts.tmp && mv ...
 *
 * Sources (all free):
 * - Uniswap default token list
 * - QuickSwap default token list
 * - Sushiswap token list
 * - Llama.fi community token list (very good coverage)
 */

type TokenListToken = {
  address: string;
  decimals: number;
  symbol?: string;
  name?: string;
};

const LISTS = [
  // Uniswap (excellent coverage)
  "https://tokens.uniswap.org",
  // QuickSwap (Polygon native)
  "https://raw.githubusercontent.com/QuickSwap/QuickSwap-info/main/src/constants/tokenLists/quickswap-default.tokenlist.json",
  // Sushiswap
  "https://raw.githubusercontent.com/sushiswap/list/master/lists/token-lists/default-token-list/tokens/polygon.json",
  // Llama.fi (very broad community list)
  "https://raw.githubusercontent.com/llamafinance/llama-token-lists/main/tokenlists/polygon.json",
];

async function fetchList(url: string): Promise<TokenListToken[]> {
  try {
    const res = await fetch(url, { headers: { "User-Agent": "hyperindex-polygon-tokens/1.0" } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = await res.json();

    // Handle both { tokens: [...] } and direct array formats
    const tokens: any[] = Array.isArray(json) ? json : json.tokens ?? [];

    return tokens
      .filter((t) => t.address && typeof t.decimals === "number")
      .map((t) => ({
        address: t.address.toLowerCase(),
        decimals: Number(t.decimals),
        symbol: t.symbol,
        name: t.name,
      }));
  } catch (e) {
    console.error(`Failed to fetch ${url}:`, e);
    return [];
  }
}

async function main() {
  console.log("// Auto-generated by scripts/generate-polygon-tokens.ts");
  console.log("// Run the script periodically to keep the list fresh.");
  console.log("// Sources: Uniswap, QuickSwap, Sushiswap, Llama.fi community lists (all free, no keys).");
  console.log("");
  console.log("export const STATIC_TOKEN_DECIMALS: Record<string, number> = {");

  const allTokens = new Map<string, number>();

  // Seed with a high-quality hand-curated core set (most important for DEX trading)
  const core: Record<string, number> = {
    "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270": 18, // WMATIC
    "0x0000000000000000000000000000000000001010": 18, // MATIC (native)
    "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619": 18, // WETH
    "0x2791bca1f2de4661ed88a30c99a7a9449aa84174": 6,  // USDC
    "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359": 6,  // USDC.e (native)
    "0xc2132d05d31c914a87c6611c10748aeb04b58e8f": 6,  // USDT
    "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063": 18, // DAI
    "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6": 8,  // WBTC
    "0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39": 18, // LINK
    "0xb33eaad8d922b1083446dc23f610c2567fb5180f": 18, // UNI (PoS)
    "0x0b3f868e0be5597d5db7feb59e1cadbb0fdda50a": 18, // SUSHI
    "0x9a71012b13ca4d3d0cdc72a177df3ef03b0e76a3": 18, // BAL
    "0x172370d5cd63279efa6d502dab29171933a610af": 18, // CRV
    "0xd6df932a45c0f255f85145f286ea0b292b21c90b": 18, // AAVE
    "0x385eeac5cb85a38a5a3a36474f0b0a5110ecf57b": 18, // GHST
    "0xb5c064f955d8e7f38fe0460c556a72987494ee17": 18, // QUICK (new)
    "0x831753dd7087cac61ab5644b308642cc1c33dc13": 18, // QUICK (old)
    "0x0b538b3a4d8b7b4c2e6e8c3f4a5b6c7d8e9f0a1b": 18, // (placeholder for script)
  };

  Object.entries(core).forEach(([addr, dec]) => allTokens.set(addr.toLowerCase(), dec));

  // Fetch and merge remote lists
  for (const url of LISTS) {
    const tokens = await fetchList(url);
    for (const t of tokens) {
      if (!allTokens.has(t.address)) {
        allTokens.set(t.address, t.decimals);
      }
    }
    console.error(`Fetched ${tokens.length} tokens from ${url}`);
  }

  // Sort by address for stable diffs
  const sorted = Array.from(allTokens.entries()).sort((a, b) => a[0].localeCompare(b[0]));

  for (const [address, decimals] of sorted) {
    console.log(`  "${address}": ${decimals},`);
  }

  console.log("};");
  console.error(`\nTotal unique tokens: ${allTokens.size}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
