#!/usr/bin/env bash
set -euo pipefail

: "${RPC_URL:?RPC_URL not set. Usage: RPC_URL=<url> PRIVATE_KEY=<key> ./d}"
: "${PRIVATE_KEY:?PRIVATE_KEY not set. Usage: RPC_URL=<url> PRIVATE_KEY=<key> ./d}"

#exec forge script script/CrossChainIntentOrigin.s.sol \
#exec forge script script/KatanaExecutor.s.sol \
exec forge script script/ArbExecutor.s.sol \
  --rpc-url "$RPC_URL" \
  --private-key "$PRIVATE_KEY" \
  --broadcast

