import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";

const abiDir = "hyperindex/abis";
const outputDir = "src/core/abis/compiled";

// Ensure output directory exists
mkdirSync(outputDir, { recursive: true });

const files = readdirSync(abiDir).filter(f => f.endsWith(".json"));
const protocolNames: string[] = [];

for (const file of files) {
  const protocol = basename(file, ".json");
  let content = JSON.parse(readFileSync(join(abiDir, file), "utf-8"));
  
  // Inject common swap functions if missing (since hyperindex abis often only have events)
  if (protocol === "uniswap_v2_pool") {
    content.push({
      type: "function",
      name: "swap",
      inputs: [
        { name: "amount0Out", type: "uint256" },
        { name: "amount1Out", type: "uint256" },
        { name: "to", type: "address" },
        { name: "data", type: "bytes" }
      ],
      outputs: [],
      stateMutability: "nonpayable"
    });
  } else if (protocol === "uniswap_v3_pool") {
    content.push({
      type: "function",
      name: "swap",
      inputs: [
        { name: "recipient", type: "address" },
        { name: "zeroForOne", type: "bool" },
        { name: "amountSpecified", type: "int256" },
        { name: "sqrtPriceLimitX96", type: "uint160" },
        { name: "data", type: "bytes" }
      ],
      outputs: [
        { name: "amount0", type: "int256" },
        { name: "amount1", type: "int256" }
      ],
      stateMutability: "nonpayable"
    });
  } else if (protocol === "uniswap_v2_factory") {
    content.push({
      type: "function",
      name: "createPair",
      inputs: [
        { name: "tokenA", type: "address" },
        { name: "tokenB", type: "address" }
      ],
      outputs: [{ name: "pair", type: "address" }],
      stateMutability: "nonpayable"
    });
  } else if (protocol === "uniswap_v3_factory") {
    content.push({
      type: "function",
      name: "getPool",
      inputs: [
        { name: "tokenA", type: "address" },
        { name: "tokenB", type: "address" },
        { name: "fee", type: "uint24" }
      ],
      outputs: [{ name: "pool", type: "address" }],
      stateMutability: "view"
    });
  }
  const constantName = protocol.toUpperCase() + "_ABI";
  const tsContent = `export const ${constantName} = ${JSON.stringify(content, null, 2)} as const;\n`;
  writeFileSync(join(outputDir, `${protocol}.ts`), tsContent, "utf-8");
  protocolNames.push(protocol);
}

// Generate index.ts
let indexContent = "// Auto-generated by scripts/compile-abis.ts\n";
for (const protocol of protocolNames) {
  indexContent += `import { ${protocol.toUpperCase()}_ABI } from "./${protocol}.ts";\n`;
}
indexContent += "\nexport {\n";
for (const protocol of protocolNames) {
  indexContent += `  ${protocol.toUpperCase()}_ABI,\n`;
}
indexContent += "};\n\n";

indexContent += "export const COMPILED_ABIS = {\n";
for (const protocol of protocolNames.sort()) {
  indexContent += `  "${protocol}": ${protocol.toUpperCase()}_ABI,\n`;
}
indexContent += "} as const;\n";

writeFileSync(join(outputDir, "index.ts"), indexContent, "utf-8");
console.log(`Successfully generated ABIs in ${outputDir}`);
