/**
 * This file is generated by HyperIndex codegen. Do not edit manually.
 * It wires project-specific types from `.envio/types.d.ts` into the `envio` module.
 * Types are now auto-refreshed by the HyperIndex wrapper on start (if schema/config changed).
 * Explicit: run `envio codegen` if needed.
 */
/// <reference path="./.envio/types.d.ts" />
