// Auto-generated by scripts/compile-abis.ts
import { ERC20_ABI } from "./erc20.ts";
import { CURVE_FACTORY_ABI } from "./curve_factory.ts";
import { WOOFI_POOL_ABI } from "./woofi_pool.ts";
import { DODO_POOL_ABI } from "./dodo_pool.ts";
import { DODO_FACTORY_ABI } from "./dodo_factory.ts";
import { UNISWAP_V2_FACTORY_ABI } from "./uniswap_v2_factory.ts";
import { UNISWAP_V4_POOL_MANAGER_ABI } from "./uniswap_v4_pool_manager.ts";
import { UNISWAP_V3_FACTORY_ABI } from "./uniswap_v3_factory.ts";
import { UNISWAP_V2_POOL_ABI } from "./uniswap_v2_pool.ts";
import { BALANCER_VAULT_ABI } from "./balancer_vault.ts";
import { CURVE_POOL_ABI } from "./curve_pool.ts";
import { UNISWAP_V3_POOL_ABI } from "./uniswap_v3_pool.ts";

export {
  ERC20_ABI,
  CURVE_FACTORY_ABI,
  WOOFI_POOL_ABI,
  DODO_POOL_ABI,
  DODO_FACTORY_ABI,
  UNISWAP_V2_FACTORY_ABI,
  UNISWAP_V4_POOL_MANAGER_ABI,
  UNISWAP_V3_FACTORY_ABI,
  UNISWAP_V2_POOL_ABI,
  BALANCER_VAULT_ABI,
  CURVE_POOL_ABI,
  UNISWAP_V3_POOL_ABI,
};

export const COMPILED_ABIS = {
  "balancer_vault": BALANCER_VAULT_ABI,
  "curve_factory": CURVE_FACTORY_ABI,
  "curve_pool": CURVE_POOL_ABI,
  "dodo_factory": DODO_FACTORY_ABI,
  "dodo_pool": DODO_POOL_ABI,
  "erc20": ERC20_ABI,
  "uniswap_v2_factory": UNISWAP_V2_FACTORY_ABI,
  "uniswap_v2_pool": UNISWAP_V2_POOL_ABI,
  "uniswap_v3_factory": UNISWAP_V3_FACTORY_ABI,
  "uniswap_v3_pool": UNISWAP_V3_POOL_ABI,
  "uniswap_v4_pool_manager": UNISWAP_V4_POOL_MANAGER_ABI,
  "woofi_pool": WOOFI_POOL_ABI,
} as const;
